### ISSUE TITLE
2018920001 강송모 '5. 발표용 ppt 마크다운으로 번역하기'

### ISSUE THREAD

**Issue by prixt** [prixt/creative_engineering_research#4]

**Comment by rkdthdah** [comment]
# 방치형 게임 시장조사 및 설계
## A++le(3조) - 강한빛 임재욱 곽수인 유윤재 강송모
---
### 우리가 만들고자 하는 게임 및 장르 분석
- 방치형: 다양한 동물을 수집하고 기르는 것이 메인 컨텐츠
- 그외 요소
    - 수집: 악세서리 및 옷 뿐만 아니라 훈련시킨 특기 또한 수집가능
    - 힐링: 귀여운 동물들
    - 커뮤니티 기능: 친구들과 대회 플레이 가능
- 방치형 게임의 장단점 분석
    - 장점
        - 개발 및 관리 용이
        - 진입장벽이 낮음
        - 많은 시간 투자 불필요
        - 장기간 사용자 많음
    - 단점
        - 경쟁작 다수
        - 지속적 업데이트 필요
        - 게임의 단조로움
        - 광고에 의한 게임진행 방해
### 경쟁작 선정 및 분석
네코아츠메, 마이 오아시스
- 개발 배경
    - 네코아츠메
        - 고양이 애호가를 타겟으로 개발
        - 고양이를 단순화하며 행동은 살림
        - 게임 자체에만 집중(광고와 같은 몰입 방해 요소 배제)
    - 마이 오아시스
        - 글로벌을 타겟으로 기획
        - 힐링을 경함할 수 있는 게임으로 기획
        - 모든 시스템에서 힐링 콘셉트를 느낄 수 있도록 함
- 특징 분석
    - 네코아츠메
        - 과금 아이템이 고양이를 많이 불러모은다
        - 만국공통의 귀여움
        - 단순한 UI및 플레이 방식
        - 앱에 머무를 필요 없음
        - 캐릭터에 대한 창작 수요가 많다
    - 마이 오아시스
        - 힐링이란 테마에 집중
        - 감성적인 음악, 효과음
        - 아기자기한 그래픽
        - 지속적인 플레이(탭) 필요
        - 인앱 광고 유도 다수
### 벤치마킹 및 게임설계
- 디자인
    - 다양한 동물들을 수집
    - 동물들과 교류하며 옷, 훈련 가능
    - **닌텐독스**의 대회, 페스티벌과 같은 교류 컨텐츠
    - **네코아츠메** 처럼 백그라운드 상태로 동물들과 만나는 것이 가능
- 수익
    - **네코아츠메**와 같이 과금, 광고를 통해 희귀한 동물들을 보다 잘 끌어들일 수 있도록 한다
    - **포켓몬고**처럼 동물의 아이템 상점을 현실 공간에 위치시켜 사람들의 방문을 유도한다
    - 현실 공간의 점유자에게 광고료를 받는다
