### ISSUE TITLE
A++le '1. 경쟁작 정리'

### ISSUE THREAD

**Issue by rkdthdah** [prixt/creative_engineering_research#6]

**Comment by JaeWookLim** [comment]
# 경쟁작 정리


* 마이 오아시스 - 힐링되는 하늘섬 키우기
  * 게임의 개요
      * 탭을 통한 하트의 획득
      * 하트를 통해 오아시스 레벨업
      * 오아시스의 레벨업으로 지형의 변화, 새로운 동식물의 등장

  * 게임의 장점
       * 게임 내에서 오아시스가 성장하는 느낌이 잘 드러남
       * 잔잔한 BGM과 음악 연주라는 컨텐츠를 통해 지속적 게임 플레이를 유도
       * 섬을 다각도로 볼 수 있어서 동식물을 보기 좋음

  * 게임의 단점
       * 광고 시청 유도가 자주 나와서 신경이 쓰임

* 전자오락수호대
   * 게임의 개요
       * 동명의 웹툰 '전자오락수호대'의 IP 기반으로 만든 방치형 게임
       * '수호대'를 고용하여 핵심 캐릭터 '용사'를 스테이지 끝에 도달하게 만드는 게임.

   * 게임의 장점
       * 인지도 높은 웹툰의 IP를 채용하여 유저층 확보에 유리
       * 유료 재화인 '다이아'를 자주 유저들에게 나누어주어 과금 부담을 줄임
       * 던전, 피라미드, PVP, 보스전 등 다양한 컨텐츠가 존재

   * 게임의 단점
       * 캐릭터들이 과도하게 많아서 캐릭터간 밸런스가 잘 맞지 않음
       * 다양한 컨텐츠가 존재하나 라이트 유저들에게는 특정 컨텐츠의 진입장벽이 지나치게 높음.

**Comment by suin0730** [comment]
# **고양이는 정말 귀여워 (2018.7.3)**

- 고양이 마을을 만드는 힐링 시뮬레이션 게임

- 개요
  - 멸치, 고양이풀, 하트 등을 모아 새로운 고양이를 발견하고 고양이의 귀여운 행동을 추가할 수 있다. 각 고양이를 발견할 때마다 고양이가 사는 건물을 짓는다.
- 강점
  - 고양이가 사는 곳에 따른 개성이 다양해 플레이어에게 새로운 즐거움을 준다.
    - 세탁소의 세탁하는 고양이 등
  - 고양이의 귀여움을 업그레이드 할 수 있다.
    - 자동문 구경하기, 하품하기 등 실제 고양이가 할법한 행동
  - 보상을 얻는 방법이 단순터치 등으로 간단하다.
    - 힐링이 목적인 게임에 적합하다.

# **Walkr – 주머니속의 우주탐험**

- 실제 본인의 걸음수를 에너지로 사용하여 새로운 외계 행성을 발견하는 탐험 게임

- 개요
  -  11살의 천재 소년이 조종실의 장치 위에서 뛰거나 걸으면 그 에너지로 우주선을 움직일 수 있어 우주의 시공간을 초월해 담험할 수 있다.

- 강점)
  - 각 행성의 컨셉과 디자인의 퀄리티가 높다.
  - 방치형의 가장 큰 특징으로, 하고싶을때만 들어가서 해도 아무 지장이 없다.
  - 행성 발견에서 끝나는 것이 아니라 토마토를 이용해 발전시킬 수 있다.
  - 랭킹제도가 있다. 
    - 친구목록의 개념
  - 연구소, 일종의 길드가 있다.
    - 연구소에 가입하거나 연구소를 생성해 연구할 행성을 정하면 연구소 내 다른 유저들의 에너지를 기부받을 수 있다.

**Comment by prixt** [comment]
정리 완료했습니다.
